import dotenvFlow from 'dotenv-flow'

dotenvFlow.config()

const {
  NODE_ENV,
  PORT,
  SERVER_URL,
  DATABASE_URL,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET,
  FRONTEND_URL,
  CORS_ORIGINS,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_FONTS_API_KEY,
  GOOGLE_CALENDAR_REFRESH_TOKEN,
  GOOGLE_CALENDAR_ID,
  GOOGLE_CALENDAR_TIMEZONE,
  FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET,
  MAIL_ADDRESS,
  MAIL_PASS,
  RESEND_MAIL_MINUTES,
  OTP_EXPIRE_MINUTES,
  FORGOT_PASSWORD_EXPIRY_MINUTES,
  PASSWORD_SETUP_EXPIRY_MINUTES,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  AWS_BUCKET,
  S3_BUCKET,
  S3_KEY_PREFIX,
  S3_PUBLIC_BASE_URL,
  VAPID_PUBLIC_KEY,
  VAPID_PRIVATE_KEY,
  VAPID_SUBJECT,
  PUBLIC_RATE_LIMIT_WINDOW_MS,
  PUBLIC_RATE_LIMIT_MAX,
  LARAVEL_MYSQL_URL,
  MEDIA_BASE_URL,
  CANVA_CLIENT_ID,
  CANVA_CLIENT_SECRET,
  CANVA_REDIRECT_URI,
  CANVA_TOKEN_ENCRYPTION_KEY,
  CANVA_SCOPES,
} = process.env

const parseCommaSeparatedList = (value?: string): string[] =>
  value
    ?.split(',')
    .map((item) => item.trim())
    .filter(Boolean) ?? []

export default {
  NODE_ENV: NODE_ENV || 'development',
  PORT: PORT || '5000',
  SERVER_URL: SERVER_URL || 'http://localhost:5000',
  DATABASE_URL,
  argon2: {
    type: 2 as const, // argon2id
    memoryCost: 65536,
    timeCost: 3,
    parallelism: 1,
  },
  REFRESH_TOKEN: {
    SECRET: REFRESH_TOKEN_SECRET,
    EXPIRY: '7d',
  },
  ACCESS_TOKEN: {
    SECRET: ACCESS_TOKEN_SECRET,
    EXPIRY: '1h',
  },
  FRONTEND_URL: NODE_ENV === 'production' ? FRONTEND_URL : FRONTEND_URL || 'http://localhost:3000',
  CORS_ORIGINS: parseCommaSeparatedList(CORS_ORIGINS),
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_FONTS_API_KEY,
  GOOGLE_CALENDAR: {
    REFRESH_TOKEN: (GOOGLE_CALENDAR_REFRESH_TOKEN || '').trim() || undefined,
    CALENDAR_ID: (GOOGLE_CALENDAR_ID || 'primary').trim(),
    TIMEZONE: (GOOGLE_CALENDAR_TIMEZONE || 'UTC').trim(),
  },
  FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET,
  MAIL_ADDRESS,
  MAIL_PASS,
  RESEND_MAIL_MINUTES: Number(RESEND_MAIL_MINUTES),
  OTP_EXPIRE_MINUTES: Number(OTP_EXPIRE_MINUTES ?? RESEND_MAIL_MINUTES),
  FORGOT_PASSWORD_EXPIRY_MINUTES: Number(FORGOT_PASSWORD_EXPIRY_MINUTES) || 15,
  PASSWORD_SETUP_EXPIRY_MINUTES: Number(PASSWORD_SETUP_EXPIRY_MINUTES) || 15,
  S3: {
    ACCESS_KEY_ID: AWS_ACCESS_KEY_ID,
    SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY,
    REGION: AWS_REGION || 'us-east-1',
    BUCKET: S3_BUCKET || AWS_BUCKET,
    KEY_PREFIX: S3_KEY_PREFIX || 'vbizme',
    PUBLIC_BASE_URL: S3_PUBLIC_BASE_URL,
  },
  VAPID: {
    PUBLIC_KEY: VAPID_PUBLIC_KEY,
    PRIVATE_KEY: VAPID_PRIVATE_KEY,
    SUBJECT: VAPID_SUBJECT || 'mailto:admin@vbizme.com',
  },
  PUBLIC_RATE_LIMIT: {
    WINDOW_MS: Number(PUBLIC_RATE_LIMIT_WINDOW_MS) || 60_000,
    MAX: Number(PUBLIC_RATE_LIMIT_MAX) || 120,
  },
  LARAVEL_MYSQL_URL,
  MEDIA_BASE_URL: MEDIA_BASE_URL || 'https://app.vbizme.com',
  CANVA_CLIENT_ID,
  CANVA_CLIENT_SECRET,
  CANVA_REDIRECT_URI,
  CANVA_TOKEN_ENCRYPTION_KEY,
  CANVA_SCOPES,
}
